name: Deploy Dynamic HTML Page

on:
  workflow_dispatch:
    inputs:
      slug:
        description: 'Unique folder name'
        required: true
      html:
        description: 'HTML content'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Create HTML file
        run: |
          mkdir -p "${{ github.event.inputs.slug }}"
          echo "${{ github.event.inputs.html }}" > "${{ github.event.inputs.slug }}/index.html"

      - name: Commit and push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Add page: ${{ github.event.inputs.slug }}" || echo "Nothing to commit"
          git push origin gh-pages
